#!/bin/bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  cat <<EOF
Usage: $0 <spec|instruction> <snippet-file>
Example: $0 spec hooks/new-feature.md
EOF
  exit 1
fi

TYPE="$1"
SNIPPET="$2"

if [[ ! -f "$SNIPPET" ]]; then
  echo "Snippet not found: $SNIPPET"
  exit 2
fi

case "$TYPE" in
"spec")
  TARGET="SPEC.md"
  DEFAULT_HEADER="# SPEC.md"
  SECTION_TITLE="## Spec Update"
  ;;
"instruction")
  TARGET="INSTRUCTION.md"
  DEFAULT_HEADER="# INSTRUCTION.md"
  SECTION_TITLE="## Instruction Update"
  ;;
*)
  echo "Unknown type: $TYPE"
  exit 3
  ;;
esac

if [[ ! -f "$TARGET" ]]; then
  cat <<EOF > "$TARGET"
$DEFAULT_HEADER

> Generated by scripts/spec_instruction_hook.sh at $(date -u +"%Y-%m-%d %H:%M UTC")

EOF
fi

TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
cat >> "$TARGET" <<EOF

$SECTION_TITLE ($TIMESTAMP)

$(cat "$SNIPPET")

EOF

echo "Updated $TARGET using snippet $SNIPPET"
